name: dabl_generator
version: 0.1.2
author: Nathan Kerr <nathankerr@gmail.com>
description: Generator for the DABL ORM
homepage: https://github.com/TheBosZ/dabl-generator
dependencies:
  args: '>=0.11.0+1 <0.12.0'
  dabl: '>=0.1.2 <0.2.0'
  database_reverse_engineer: '>=0.1.1 <0.2.0'
dev_dependencies:
  unittest: any
