name: dabl_generator
version: 0.1.2
author: Nathan Kerr <nathankerr@gmail.com>
description: Generator for the DABL ORM
homepage: https://github.com/TheBosZ/dabl-generator
dependencies:
  args: '>=0.11.0+1 <0.12.0'
  dabl: 
    path: ../dabl-dart
  database_reverse_engineer: 
    path: ../database_reverse_engineer
dev_dependencies:
  unittest: any
